### ISSUE TITLE
le monarque red mark

### ISSUE THREAD

**Issue by YamazakiRobert** [marquesinijatinha/littlelight_translations#27]
the le monarque have a red block on the equipment, the vault are okay

**Comment by RaSSieL86** [comment]
Hi! The developer already has proof of that problem. Other exceptional weapons such as Jotum, Izanagi and Splitwaves also have the same error. You are already looking for a solution.

I recommend that you join the Discord server to be able to do the feedback there.

**Comment by marquesinijatinha** [comment]
Thanks for the report @YamazakiRobert 
@RaSSieL86 actually is easier to track issues here as I have a history and can keep track of what I already fixed and what I didn't

**Comment by marquesinijatinha** [comment]
Fixed in 1.5.3
